// Generated by CoffeeScript 1.6.3
'use strict';
var protractor;


describe('E2E: Login', function() {

  beforeEach(function() {
    browser.get('http://localhost:9000/');
  });

  describe('when the user logs in', function() {
    it('should redirect he to the main page and he should see a message', function() {
      element(global.by.input('credentials.email')).sendKeys('test_1@gmail.com');
      element(global.by.input('credentials.password')).sendKeys('test1');
      element(global.by.id('log-in')).click();
      element(global.by.binding('{{ message }}')).getText().then(function(text) {
        expect(text).toEqual('foobar');
      });
    });
  });

});
